# Generated by Django 5.1.5 on 2025-02-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerinput',
            name='climate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerinput',
            name='land_dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerinput',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
